### ISSUE TITLE
craco 7 with official react-scripts v5 support has been released

### ISSUE THREAD

**Issue by abenhamdine** [DocSpring/craco-less#102]
see https://github.com/dilanx/craco/releases/tag/v7.0.0

I think it's now possible to roll out a new version of craco-less with craco 7 as peerDependency

**Comment by justinwaite** [comment]
@abenhamdine are there any breaking changes from v7 that need to be addressed, or would this simply be a bump to the peer dep range?

**Comment by abenhamdine** [comment]
> @abenhamdine are there any breaking changes from v7 that need to be addressed, or would this simply be a bump to the peer dep range?

I don't think so, the goal for craco 7 was to support react-scripts 5 and webpack 5, no other change was planned.

**Comment by karanmaster250795** [comment]
For Latest Node LTS 18.12.1 with @craco/craco 7.0.0, we need to use 2.1.0-alpha.0 version of craco-less, is there any way without alpha or is there any plan to release stable that support it?
