### ISSUE TITLE
When installing `craco-less`, is it more appropriate to install it as a development dependency?

### ISSUE THREAD

**Issue by codersjj** [DocSpring/craco-less#116]
not:

```shell
$ yarn add craco-less

# OR

$ npm i -S craco-less
```

but:

```shell
$ yarn add -D craco-less

# OR

$ npm i -D craco-less
```

**Comment by kamronbatman** [comment]
Yep that is correct. I am not home to make a PR, if someone makes one I'll approve it.

**Comment by codersjj** [comment]
> Yep that is correct. I am not home to make a PR, if someone makes one I'll approve it.

I've submitted a PR.
