### ISSUE TITLE
Recommendation for this vs. craco recipe for less-loader

### ISSUE THREAD

**Issue by rojobuffalo** [DocSpring/craco-less#19]
Hi, which is the recommended way of adding less support to create-react-app? This repo looks like it serves the same purpose as this recipe/example in the main craco project: https://github.com/sharegate/craco/tree/00ae1a4364bfbe5b1ef7d5f5d89affc030c46c1f/recipes/use-less-loader . 

Are there any trade-offs or different plans for these two approaches?

**Comment by ndbroadbent** [comment]
Hello, I would recommend using this craco-less package, because it is updated and maintained by the community. The recipe was just an example that I added before creating this package, and I think it is out of date now.
