### ISSUE TITLE
Class constructor FileManager cannot be invoked without 'new'

### ISSUE THREAD

**Issue by alexandrtovmach** [DocSpring/craco-less#21]
Faced with this issue on [Semantic UI theming](https://react.semantic-ui.com/theming/)

If I'm not wrong need to fix `less` dependencies regard to:
[https://github.com/less/less.js/issues/3414](https://github.com/less/less.js/issues/3414)

**Comment by alexandrtovmach** [comment]
@ndbroadbent Hey, could you take a look on this issue and my PR with solution?

**Comment by ndbroadbent** [comment]
Hey thanks for the PR! Will take a look

**Comment by ndbroadbent** [comment]
Hi @alexandrtovmach, thanks for the PR! I also merged PR #20 to add support for the latest CRA. Please check out the new version and let me know if that fixes the issue for you!

**Comment by alexandrtovmach** [comment]
@ndbroadbent 
Tested with my project and found another issue related to "less":
![image](https://user-images.githubusercontent.com/28801003/63321620-f4399280-c329-11e9-89af-ee551888a517.png)

Problem is caused by:
![image](https://user-images.githubusercontent.com/28801003/63322158-678fd400-c32b-11e9-81b5-0f4009230192.png)


Here is fix #23

**Comment by ndbroadbent** [comment]
Thanks @alexandrtovmach! I have released this change in version `1.12.0`.

I was wondering if you might be interested in helping to maintain this project? I am actually not using it at the moment (but am planning to migrate to CRA and starting using it in the future.) In the meantime, I would be happy to add you as a maintainer if you are interested!

**Comment by alexandrtovmach** [comment]
@ndbroadbent Fix tested ― seems okay. Thank you for quick support 👍

> to maintain this project

Yes, I'd happy to help

**Comment by AustinGreen** [comment]
Thank you both. This fix is much appreciated

**Comment by ndbroadbent** [comment]
Thanks @alexandrtovmach! I've given you write access as a collaborator, so please feel free to help with any issues or PRs, and let me know whenever you would like me to push a new version of the NPM package. Thanks!
