### ISSUE TITLE
Update Less-Loader

### ISSUE THREAD

**Issue by AO19** [DocSpring/craco-less#40]
Hey 👋 

Could you please update less-loader to the latest version/ or `less-loader@next`?

It is needed to use this package with the  latest version of Ant Design.
~Also the maintainer of less-loader just changed, and it is on version 6.x now.~

**Comment by ndbroadbent** [comment]
Hello, sorry I also don't have a lot of time to maintain this project, but I would be very to merge a PR if all the tests are passing + high test coverage
