### ISSUE TITLE
Error: Found an unhandled loader

### ISSUE THREAD

**Issue by SimonaliaChen** [DocSpring/craco-less#49]
Hi，
I am using `craco-antd` to customize antd theme,  while I have modified `sass-loader` options with `sass-resouces-loader`.
 
![image](https://user-images.githubusercontent.com/36978416/91269984-89c3f980-e7aa-11ea-9685-da83de89593d.png)

Then I got _Error: Found an unhandled loader in the development webpack config: sass-resources-loader_
I checked the source code, you throw an error when loader not match at https://github.com/DocSpring/craco-less/blob/586ca79b2d268d5b2a0a469a2094fa0dfe2ee733/lib/craco-less.js#L119

I wonder why have do this，is it any better to ignore irrelavant loaders?

**Comment by kamronbatman** [comment]
This should be working now.
