### ISSUE TITLE
craco:  *** Cannot find ESLint loader (eslint-loader). ***

### ISSUE THREAD

**Issue by su-dd** [DocSpring/craco-less#52]
npm start

> blog-app@0.1.0 start G:\blog-react\blog-app
> craco start

craco:  *** Cannot find ESLint loader (eslint-loader). ***
(node:1212) UnhandledPromiseRejectionWarning: Error: Found an unhandled loader in the development webpack config: G:\blog-react\blog-app\node_modules\_style-loader@1.3.0@style-loader\dist\cjs.js

This error probably occurred because you updated react-scripts or craco. Please try updating craco-less to the latest version:

   $ yarn upgrade craco-less

Or:

   $ npm update craco-less

**Comment by pengcheng789** [comment]
Need to support for react-scripts `^4.0.0`.

**Comment by goblin2018** [comment]
not work for react-scripts ^4.0.0

craco now supports:
Create React App (CRA) 3.*

just set "react-scripts": "3.4.1", in package.json

**Comment by shantiscript** [comment]
Is there an update coming in the  future for react-scripts 4.00?

**Comment by tux-tn** [comment]
This issue is not related to craco-less . Craco doesn't support CRA 4 yet. You can see support progress here https://github.com/gsoft-inc/craco/pull/219

**Comment by yurikhan** [comment]
As far as I understand, @craco/craco properly supports react-scripts ≥4 starting with version 6.0.0. However, all craco-less versions up to and including craco-less@1.17.1 specify @craco/craco: ^5.5.0 as a peer dependency.

**Comment by nhevia** [comment]
@tux-tn gsoft-inc/craco#219 was merged, this needs to be reopened and update deps for craco to 6.0.0.
