### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by pguardiario** [DocSpring/craco-less#55]
npm i craco-less gives the following errors:

npm ERR! Found: @craco/craco@6.0.0
npm ERR! node_modules/@craco/craco
npm ERR!   @craco/craco@"^6.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @craco/craco@"^5.5.0" from craco-less@1.17.1       
npm ERR! node_modules/craco-less
npm ERR!   craco-less@"*" from the root project

Does anyone have a fix for this?

**Comment by anasnajaa** [comment]
I belive you can fix this issue by specifying the craco build version.
For example, try to set these packages into your package.json: 
`"@craco/craco": "^5.5.0",
"craco-less": "^1.17.1",
`and try to run `npm install` again.
Package maintainers need to pump the dependency version.

**Comment by pguardiario** [comment]
craco@5.5.0 is missing for me. I think someone needs to update that to 6.0.0

**Comment by wapenshaw** [comment]
No update on this?

I'm having the same issue 

![image](https://user-images.githubusercontent.com/739546/107844590-94139780-6dcc-11eb-9de2-7f53d32e4e3a.png)

**Comment by tux-tn** [comment]
Sorry for the delay guys, i'm taking a look at it

**Comment by wapenshaw** [comment]
> 
> 
> Sorry for the delay guys, i'm taking a look at it


This is a weird issue for me, I was able to get it working using yarn but somehow it doesn't work with npm currently. I don't understand. In my case here is my `package.json`

```json
"dependencies": {
		"@craco/craco": "^6.1.1",
		"@types/node": "^14.14.25",
		"@types/react": "^17.0.1",
		"@types/react-big-calendar": "^0.30.0",
		"@types/react-dom": "^17.0.0",
		"@types/react-router-dom": "^5.1.7",
		"antd": "^4.12.2",
		"axios": "^0.21.1",
		"babel-plugin-import": "^1.13.3",
		"craco-less": "^1.17.1",
		"eslint-config-prettier": "^7.2.0",
		"eslint-plugin-prettier": "^3.3.1",
		"oidc-react": "^1.1.6",
		"react": "^17.0.1",
		"react-big-calendar": "^0.31.0",
		"react-dom": "^17.0.1",
		"react-router-dom": "^5.2.0",
		"react-scripts": "4.0.2",
		"source-map-explorer": "^2.5.2",
		"typescript": "^4.1.3"
	},
```

**Comment by tux-tn** [comment]
NPM v7 started installing [peer dependencies](https://github.com/npm/rfcs/blob/latest/implemented/0025-install-peer-deps.md) when you run `npm install` .
`craco-less` have `@craco/craco@5.5.0` as a peer-dependency and your package.json is requesting `@craco/craco@6.1.1`  that's why NPM v7 is failing and not npm v7 or yarn. 

The good way to fix this is to have a new version of `craco-less` that lists craco@6 as a peer-dependency

**Comment by birksy89** [comment]
@tux-tn could you please explain the steps needed to achieve this:

>"The good way to fix this is to have a new version of craco-less that lists craco@6 as a peer-dependency"

I'm not quite sure what you meant. 🙏
