### ISSUE TITLE
Omit error option

### ISSUE THREAD

**Issue by lywTYH** [DocSpring/craco-less#81]
```
  let lessRule = createLessRule({
    baseRule: sassRule,
    overrideRule: {
      test: lessRegex,
      exclude: lessModuleRegex,
    },
  });
```
Sass options cannot be used by less (E.g  `prependData`). Please omit it.

**Comment by fanck0605** [comment]
For the current version(4.0.3) of create-react-app, these sass specific options are not included in the rule of sass.

https://github.com/facebook/create-react-app/blob/v4.0.3/packages/react-scripts/config/webpack.config.js#L162
