### ISSUE TITLE
craco-less 2.0.0 requires react-scripts 5 but that's incompatible with craco 6.4.3

### ISSUE THREAD

**Issue by schvenk** [DocSpring/craco-less#92]
I can't seem to find versions of `react-scripts` and `craco` that are compatible with both `craco-less` 2.0.0 and each other.

`craco` 6.4.3 requires `react-scripts 4` but then I get this error saying `craco-less` needs `react-scripts` 5:
```
npm ERR! Found: react-scripts@4.0.3
npm ERR! node_modules/react-scripts
npm ERR!   react-scripts@"4.0.3" from the root project
npm ERR!   peer react-scripts@"^4.0.0" from @craco/craco@6.4.0
npm ERR!   node_modules/@craco/craco
npm ERR!     @craco/craco@"6.4.0" from the root project
npm ERR!     peer @craco/craco@"^6.0.0" from craco-less@2.0.0
npm ERR!     node_modules/craco-less
npm ERR!       craco-less@"2.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-scripts@"^5.0.0" from craco-less@2.0.0
npm ERR! node_modules/craco-less
npm ERR!   craco-less@"2.0.0" from the root project
```

If instead I install the `craco` 7 alpha and `react-scripts` 5, `craco-less` doesn't like the `craco` version:
```
npm ERR! Found: @craco/craco@7.0.0-alpha.0
npm ERR! node_modules/@craco/craco
npm ERR!   @craco/craco@"^7.0.0-alpha.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @craco/craco@"^6.0.0" from craco-less@2.0.0
npm ERR! node_modules/craco-less
npm ERR!   craco-less@"2.0.0" from the root project
```

What's the right answer here?

**Comment by dev-afzy** [comment]
Is there any update on this issue? waiting for this :)

**Comment by GisCat** [comment]
Is there an update comming soon or we should wait for `craco` v7 ?

**Comment by edwardzjl** [comment]
I switched back to `craco-less 1.20.0` with `craco 6.4.3` and `react-scripts 4.0.3` which works

**Comment by idrissi-hamza** [comment]
try this : npm config set legacy-peer-deps true

**Comment by loreggia** [comment]
Using NPM 8 the following package.json override works, so you don't have to set the legacy-peer-deps switch:
```
  "devDependencies": {
    "@craco/craco": "^7.0.0-alpha.3",
    ...
  },
  "overrides": {
    "craco-less": {
      "@craco/craco": "$@craco/craco"
    }
  },
```

**Comment by kamronbatman** [comment]
I'll look into downgrading react-scripts to 4 and releasing a fix for v2.

**Comment by tux-tn** [comment]
I'm really sorry guys for the delays.
For people wanting to use craco-less with CRA 5 and Craco v7 a new pre-release have been published on NPM.
And for some back-story. The changes introduced in craco-less 2.0.0 are meant to make it work with CRA5, hence the major version bump. At the time of the update (just before Christmas) Craco v7 alpha was not published yet and the peer-dependency issues are only relative to npm (I guess it's related to the fact that yarn and npm are managing dependencies in different ways). 
As a temporary fix (until craco v7 is released) I suggest we add an entry to the readme with compatibility table between craco-less and cra/craco and recommend to people using npm to install the new alpha version.
